[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = [
    "probe-rs",
    "run",
    "--chip",
    "RP2040",
    "--protocol",
    "swd",
    "--speed",
    "16000",
    "--log-format",
    "{{[{L}]%bold} {f}:{l}%35} {s}",
]

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
WIFI_SSID = "gardenway"     # replace with your own value
WIFI_PASSWORD = "gardenway" # same
